In [1]:
%load_ext autoreload
%load_ext line_profiler
%autoreload 2

In [2]:
import logging
import collections
import pathlib

import torch
import numpy as np
import numpy.ma as ma
import pandas as pd

import hyclib as lib
from hyclib.bpd import array as ar

Loaded default config file at /Users/hoyinchau/local_documents/research/utils/utils/config.toml.
Loaded user config files at the following locations from highest to lowest priority: [PosixPath('utils_config.toml'), PosixPath('/Users/hoyinchau/local_documents/research/utils/configs/utils_config.toml'), PosixPath('/Users/hoyinchau/Library/Application Support/utils/config.toml')]


In [3]:
print(lib.cfg['params']['a'])
print(lib.cfg['params']['b'])
print(lib.cfg['params']['c'])
print(lib.cfg['params']['d'])
lib.cfg['params']['b'] = 4
print(lib.cfg['params']['b'])

1st user config
2nd user config
3rd user config
default config
4


In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
print(device)

lib.logging.basic_config()
logger = logging.getLogger()

mps


In [9]:
arr = np.array([0, 1, 2, 10, 11, 20, 21, 22, 23])
chunks = np.array([3, 2, 4])
repeats = np.array([1, 3, 2])
print(lib.np.repeat(arr, repeats, chunks=chunks))

[ 0  1  2 10 11 10 11 10 11 20 21 22 23 20 21 22 23]


In [5]:
data = torch.normal(mean=0.0, std=1.0, size=(10,5))
index = list(range(len(data)))[::-1]
columns = ['a','b','c','d','e']
df = pd.DataFrame(data, index=index, columns=columns)
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
# tdf[['f','g'], 2:5] = [torch.tensor(1, device=device), np.array(2)]

In [6]:
lib.pd.display(df, max_rows=10)
lib.pd.display(tdf.to_pandas(), max_rows=10)
lib.pd.display(tdf, max_rows=10)

In [4]:
def rand_string(length, size=None, chars=None, varlength=True):
    if chars is None:
        chars = 'abcdefghijklmnopqrstuvwxyz'
    chars = np.array(list(chars))

    if size is None:
        size = (1,)
    elif isinstance(size, int):
        size = (size,)
    
    if not isinstance(size, tuple):
        raise TypeError(f"size must be a tuple, but {type(size)=}.")
    
    shape = (*size, length)
    s = chars[np.random.randint(len(chars), size=shape)].reshape(-1, length)
    mask = np.random.randint(2, size=s.shape, dtype=bool)
    mask[:,0] = True
    s = np.array([''.join(si[maski]) for si, maski in zip(s, mask)]).reshape(size)
    return s.squeeze()

In [138]:
N, Ma, Mb, chars = 100000, 10, 10, 'pqrstuvwxyz'
data1 = {
    'c': torch.from_numpy(np.random.normal(size=N)),
    'b': rand_string(Mb, size=N, chars=chars),
    'a': np.random.randint(Ma, size=N),
}
data2 = {
    'a': np.random.randint(Ma, size=N),
    'd': rand_string(Mb, size=N, chars=chars),
    'c': np.random.normal(size=N),
}
tdf1 = lib.bpd.DataFrame(data1)
tdf2 = lib.bpd.DataFrame(data2)
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [96]:
lib.pd.display(df1)
lib.pd.display(df2)

In [117]:
%lprun -f lib.bpd.DataFrame.merge -f lib.bpd.concat -f lib.bpd.DataFrame._to_numpy_numeric tdf1.merge(tdf2)

Timer unit: 1e-06 s

Total time: 0.044494 s
File: /Users/hoyinchau/local_documents/research/utils/utils/bpd/dataframe.py
Function: _to_numpy_numeric at line 383

Line #      Hits         Time  Per Hit   % Time  Line Contents
   383                                               def _to_numpy_numeric(self):
   384         1          0.0      0.0      0.0          arrs = []
   385         3          8.0      2.7      0.0          for arr in self._values():
   386         2          9.0      4.5      0.0              arr = arr.detach().cpu().numpy() # do everything in numpy due to various torch.unique bugs
   387         2          3.0      1.5      0.0              if arr.dtype.kind not in 'biufc': # non-numeric
   388         1      44049.0  44049.0     99.0                  _, arr = np.unique(arr, return_inverse=True)
   389         2          3.0      1.5      0.0              if isinstance(arr, ma.MaskedArray):
   390                                                           arr = arr

In [120]:
%%timeit
tdf1.merge(tdf2)

72.1 ms ± 542 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [119]:
%%timeit
df1.merge(df2)

32.6 ms ± 999 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [582]:
(tdf1['a'] == b) & ~(tdf1['b'] == cd)

array([False, False, False, ..., False, False, False])

In [604]:
b = 1
cd = 'x'
expr = '`a` == @b and b == @cd'
lib.pd.display(tdf1.query(expr))
lib.pd.display(df1.query(expr))

In [139]:
with lib.logging.set_level(logger, 'INFO'):
    tdf12 = tdf1.merge(tdf2, left_on=['a','b'], right_on=['a','d'])
    df12 = df1.merge(df2, left_on=['a','b'], right_on=['a', 'd'])
# out = tdf12.to_pandas().merge(df12, validate='1:1')
# assert len(tdf12) == len(out) == len(df12)
lib.pd.display(tdf12, max_rows=10)
lib.pd.display(df12, max_rows=10)
# lib.pd.display(tdf12.info())
# print(df12.memory_usage())

In [4]:
data1 = {
    'a': [  1,  1,  2,  2,  2,  3,  3],
    'b': ['a','b','c','d','d','e','f'],
    'c': [ 16, 17, 18, 30, 19, 20, 21],
}
data2 = {
    'a': [  1,  1,  2, 2, 13, 14, 15],
    'b': ['e','b','c','d','d','e','f'],
    'd': [ 22, 23, 24, 31, 25, 26, 27],
}

In [8]:
tdf1 = lib.bpd.DataFrame(data1)
tdf2 = lib.bpd.DataFrame(data2)
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
print(df1)
print(df2)
lib.pd.display(tdf1.merge(tdf2), max_rows=np.inf)
lib.pd.display(df1.merge(df2), max_rows=10)

   a  b   c
0  1  a  16
1  1  b  17
2  2  c  18
3  2  d  30
4  2  d  19
5  3  e  20
6  3  f  21
    a  b   d
0   1  e  22
1   1  b  23
2   2  c  24
3   2  d  31
4  13  d  25
5  14  e  26
6  15  f  27


In [5]:
class Hi:
    def __init__(self, a):
        self.a = a
        
    def __le__(self, value):
        return self.a <= value.a
    
    def __lt__(self, value):
        return self.a < value.a
    
    def __ge__(self, value):
        return self.a >= value.a
    
    def __gt__(self, value):
        return self.a > value.a
    
    def __eq__(self, value):
        return self.a == value.a

In [26]:
a = np.random.randint(5,size=(30,2))
print(np.unique(a, return_inverse=True, return_counts=True, axis=0))
print(lib.np.unique_rows(a, return_inverse=True, return_counts=True))

(array([[0, 0],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 1],
       [3, 2],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4]]), array([13,  8,  7, 12, 11,  3,  5,  1,  4,  8,  6,  1, 13,  9,  8, 13, 11,
        2,  1,  1,  4, 11,  6,  6, 10,  0,  6, 12, 10,  9]), array([1, 4, 1, 1, 2, 1, 4, 1, 3, 2, 2, 3, 2, 3]))
[array([[0, 0],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 1],
       [3, 2],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4]]), array([13,  8,  7, 12, 11,  3,  5,  1,  4,  8,  6,  1, 13,  9,  8, 13, 11,
        2,  1,  1,  4, 11,  6,  6, 10,  0,  6, 12, 10,  9]), array([1, 4, 1, 1, 2, 1, 4, 1, 3, 2, 2, 3, 2, 3])]


In [12]:
N, M = 10,3
data = torch.normal(mean=0.0, std=1.0, size=(N,5), requires_grad=True)
index = list(range(len(data)))[::-1]
columns = ['a','b','c','d','e']
df = pd.DataFrame(data.detach().cpu().numpy(), index=index, columns=columns)
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
tdf['g'] = ma.array(np.random.randint(M, size=N), mask=False)+1
tdf['g', [1,3,5]] = lib.bpd.NA
tdf['g2'] = ma.array(np.random.randint(M, size=N), mask=False)+1
tdf['g2', 2] = lib.bpd.NA
# tdf['g'] = ma.array(1, mask=True)
# tdf['g', [1,3,5]] = [1,2,3]
# tdf['f'] = torch.tensor(2, device=device)
# tdf['f',5:] = 3
tdf['f'] = Hi(2)
tdf['f',5:] = Hi(3)

tdf = tdf.to('cpu')
# tdf['b'] = tdf['b'].numpy()
df = tdf.to_pandas()

In [102]:
arr = tdf[['g','g2','f']].to_numpy()
print(arr.dtype)
print(lib.np.unique_rows(arr))

object


TypeError: Cannot change data-type for object array.

In [82]:
# lib.pd.display(tdf.info(), max_rows=10)
lib.pd.display(tdf, max_rows=10)
# lib.pd.display(tdf.to_pandas(), max_rows=10)

In [13]:
kwargs = {f'{k}_b': ('b', k) for k in ['count', 'sum', 'mean', 'var', 'std', 'sem', 'min', 'max']}
tgdf = tdf.groupby(['g', 'g2', 'f'], dropna=False).agg(
    **kwargs
)
# gdf = df.groupby(['g', 'g2', 'f'], as_index=False, dropna=False).agg(
#     **kwargs
# )

In [109]:
# np.isnan(np.array([None]))

In [14]:
lib.pd.display(tgdf, max_rows=10)
lib.pd.display(gdf, max_rows=10)

NameError: name 'gdf' is not defined

In [38]:
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
tdf[['f','g'], 2:5] = [torch.tensor(1, device=device), np.array(2)]
print(tdf)
print(tdf.info())
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
tdf[['f','g'], 2:5] = [torch.tensor([1,2,3], device=device), np.array([2,3,1])]
print(tdf)
print(tdf.info())
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
tdf[['f','g'], 2:5] = [torch.tensor([1,2,3], device=device)]
print(tdf)
print(tdf.info())
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
try:
    tdf[['f','g'], 2:5] = torch.tensor([1,2,3], device=device)
except (RuntimeError, ValueError) as err:
    print(err)
tdf = lib.bpd.DataFrame(data.to(device), columns=columns)
try:
    tdf[['f','g'], 2:5] = [1,2,3]
except (RuntimeError, ValueError) as err:
    print(err)

          a         b         c         d         e    f    g
0  1.410362  0.333303  0.405563 -0.932654 -0.497698  NaN  NaN
1 -0.442263 -0.624174 -0.119826 -1.590070 -0.904338  NaN  NaN
2 -0.180317 -0.292788  1.188120  0.383760  0.484597  1.0  2.0
3 -0.173698 -0.172302  0.429156 -1.149883 -0.734977  1.0  2.0
4 -0.024229 -0.546922  0.598683  0.316125 -1.638973  1.0  2.0
5  0.231934  1.055170  0.225477  0.481460 -1.018389  NaN  NaN
6  0.958846 -0.903313 -0.554520 -0.749034 -0.821387  NaN  NaN
7 -0.871738 -1.509601  0.531835 -0.037344 -0.065236  NaN  NaN
8  2.003162 -0.641635  0.637921 -0.516192  1.780537  NaN  NaN
9 -0.657648  0.569463  0.375492  2.407035  0.477876  NaN  NaN
  column  n_rows  is_tensor          dtype device  nbytes
0      a      10       True  torch.float32  mps:0     200
1      b      10       True  torch.float32  mps:0     200
2      c      10       True  torch.float32  mps:0     200
3      d      10       True  torch.float32  mps:0     200
4      e      10       True 

In [50]:
lib.pd.display(tdf.info(), max_rows=10)

In [34]:
tdf[:,['f']] = [torch.tensor(2.0, device=device)]

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [31]:
lib.pd.display(tdf, max_rows=10)
lib.pd.display(tdf.info(), max_rows=10)

In [5]:
data = {'g': [1,2,1,3,4,5,1,6,3,5]}
groups = pd.DataFrame(data, index=df.index)
tgroups = lib.bpd.DataFrame({k: torch.tensor(v) for k, v in data.items()}, index=tdf.index)

data = torch.normal(mean=0.0, std=1.0, size=(2,5))
columns = ['a','b','c','d','e']
rows = pd.DataFrame(data, columns=columns)
trows = lib.bpd.DataFrame(data, columns=columns)

In [6]:
lib.pd.display(pd.concat([df, rows], axis=0))
lib.pd.display(pd.concat([df, groups], axis=1))

In [7]:
lib.pd.display(lib.bpd.concat([tdf, trows], axis=0).reset_index())
lib.pd.display(lib.bpd.concat([tdf, tgroups], axis=1))

In [23]:
lib.pd.display(tdf, max_rows=torch.inf)

In [124]:
class Hi:
    def __init__(self, a):
        self.a = a
    def __repr__(self):
        return f'Hi({self.a})'
df = pd.DataFrame({'a': [1,2], 'b': torch.tensor([[1,2],[3,4]])})
df[np.array(['d', 'e'])] = [[1,2],[3,4]]
# df[[['d', 'e'],['f','g']]] = [[1,2],[3,4]]
print(df)

ValueError: Data must be 1-dimensional

In [28]:
data = torch.normal(mean=0.0, std=1.0, size=(10,5))
index = list(range(len(data)))[::-1]
columns = ['a','b','c','d','e']
df = pd.DataFrame(data, index=index, columns=columns)
tdf = lib.bpd.DataFrame(data, index=index, columns=columns)

data = {'g': [1,2,1,3,4,5,1,6,3,5]}
groups = pd.DataFrame(data, index=df.index)
tgroups = lib.bpd.DataFrame({k: torch.tensor(v) for k, v in data.items()}, index=tdf.index)

tdf = lib.bpd.concat([tdf, tgroups], axis=1)
tdf.groupby(['g']).agg(
    count=('a', 'count'),
    sum=('a', 'sum'),
    mean=('a', 'mean'),
    var=('a', 'var'),
    std=('a', 'std'),
    sem=('a', 'sem'),
    min=('a', 'min'),
    max=('a', 'max'),
)

     g  count       sum      mean       var       std       sem       min  \
0  1.0    3.0  1.835014  0.611671  0.932795  0.965813  0.557613 -0.417441   
1  2.0    1.0 -0.231530 -0.231530       NaN       NaN       NaN -0.231530   
2  3.0    2.0  1.069503  0.534752  0.506227  0.711497  0.503104  0.031648   
3  4.0    1.0  1.560121  1.560121       NaN       NaN       NaN  1.560121   
4  5.0    2.0  0.188752  0.094376  2.766508  1.663282  1.176118 -1.081742   
5  6.0    1.0  1.990457  1.990457       NaN       NaN       NaN  1.990457   

        max  
0  1.498372  
1 -0.231530  
2  1.037856  
3  1.560121  
4  1.270494  
5  1.990457  

In [53]:
a = pd.DataFrame({
    'a': ['a','c','a','d','b','f','b'],
    'b': [9,8,7,6,5,4,3],
})
print(a.iloc[0])
for k, v in a.groupby('a'):
    print(type(k))
    print(v)

a    a
b    9
Name: 0, dtype: object
<class 'str'>
   a  b
0  a  9
2  a  7
<class 'str'>
   a  b
4  b  5
6  b  3
<class 'str'>
   a  b
1  c  8
<class 'str'>
   a  b
3  d  6
<class 'str'>
   a  b
5  f  4


In [24]:
a = pd.DataFrame({
    'a': [1,2,3,4],
    'b': [4,5,6,7],
})
b = pd.DataFrame({
    'a': [1,3,5],
    'c': [7,8,9]
})
print(a.merge(b, how='right'))

   a    b  c
0  1  4.0  7
1  3  6.0  8
2  5  NaN  9


In [39]:
torch.unique(torch.tensor([
    [1,2,2],
    [1,2,2],
    [1,3,3],
    [3,2,2],
    [1,1,1],
    [3,4,4],
]), return_inverse=True, dim=0)

(tensor([[1, 1, 1],
         [1, 2, 2],
         [1, 3, 3],
         [3, 2, 2],
         [3, 4, 4]]),
 tensor([1, 1, 2, 3, 0, 4]))