In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import scipy.stats as stats

import hyclib as lib

In [3]:
y = np.array(
    [[[ 0.03476371,  0.17975505, -0.54908644, -0.64903577],
      [-0.03724603,  1.81708173, -0.36515959,      np.inf],
      [ 0.41836838,      np.nan, -0.49636453,  0.18997459]],

     [[ 1.466666  ,  1.0255607 ,      np.nan, -1.31296034],
      [ 1.08370192, -0.09796155, -0.05370452, -0.34803141],
      [ 0.13195273, -1.43293285,  0.82484756,  0.83380857]]]
)

yerr = np.array(
    [[[ 0.49388935,  0.99288461,  2.16113518,  3.01975125],
      [-1.50622019,  0.34152895,  0.2847713 ,  1.57976904],
      [-0.51299135,      np.nan, -0.3417016 , -1.43069183]],

     [[ 0.95822919,  1.41162136,      np.inf,  0.36485372],
      [-1.15548473, -0.08944152,  0.60378143,      np.nan],
      [-1.15460362, -0.007127  , -0.51625072,  0.18837434]]]
)

In [4]:
print(repr(y))
print(repr(yerr))
print(y.shape)
for axis in [None, 1, (1,2)]:
    # print(lib.np.mean(y, axis=axis))
    # print(lib.np.nanmean(y, axis=axis))
    # print(lib.np.sem(y, axis=axis))
    # print(stats.sem(y, axis=axis))
    # print(lib.np.nansem(y, axis=axis))
    # print(np.array(stats.sem(y, axis=axis, nan_policy='omit')))
    print(lib.np.count(y, axis=axis))
    print(lib.np.nancount(y, axis=axis))
    # print(lib.np.meanerr(y, yerr, axis=axis))
    # print(lib.np.nanmeanerr(y, yerr, axis=axis))

array([[[ 0.03476371,  0.17975505, -0.54908644, -0.64903577],
        [-0.03724603,  1.81708173, -0.36515959,         inf],
        [ 0.41836838,         nan, -0.49636453,  0.18997459]],

       [[ 1.466666  ,  1.0255607 ,         nan, -1.31296034],
        [ 1.08370192, -0.09796155, -0.05370452, -0.34803141],
        [ 0.13195273, -1.43293285,  0.82484756,  0.83380857]]])
array([[[ 0.49388935,  0.99288461,  2.16113518,  3.01975125],
        [-1.50622019,  0.34152895,  0.2847713 ,  1.57976904],
        [-0.51299135,         nan, -0.3417016 , -1.43069183]],

       [[ 0.95822919,  1.41162136,         inf,  0.36485372],
        [-1.15548473, -0.08944152,  0.60378143,         nan],
        [-1.15460362, -0.007127  , -0.51625072,  0.18837434]]])
(2, 3, 4)
24
22
[[3 3 3 3]
 [3 3 3 3]]
[[3 2 3 3]
 [3 3 2 3]]
[12 12]
[11 11]


In [91]:
hi = np.array([[ 1.466666  ,  1.0255607 ,         np.nan, -1.31296034],
[ 1.08370192, -0.09796155, -0.05370452, -0.34803141],
[ 0.13195273, -1.43293285,  0.82484756,  0.83380857]])
hi = hi[~np.isnan(hi)]
print(np.std(hi, ddof=1)/len(hi)**0.5)

0.29033110512231797


In [68]:
(0.99288461**2 + 0.34152895**2)**0.5/2

0.5249909219365023

In [65]:
(0.49388935**2 + 1.50622019**2 + 0.51299135**2)**0.5/3

0.5553563496612764

In [64]:
print((0.49388935**2 + 1.50622019**2 + 0.51299135**2))

2.7757860759818813


In [63]:
print(0.49388935**2, 1.50622019**2, 0.51299135**2)

0.24392669004342252 2.2686992607636363 0.26316012517482246


In [61]:
print(yerr**2)

[[[2.43926690e-01 9.85819849e-01 4.67050527e+00 9.11889761e+00]
  [2.26869926e+00 1.16642024e-01 8.10946933e-02 2.49567022e+00]
  [2.63160125e-01            nan 1.16759983e-01 2.04687911e+00]]

 [[9.18203181e-01 1.99267486e+00            nan 1.33118237e-01]
  [1.33514496e+00 7.99978550e-03 3.64552015e-01            nan]
  [1.33310952e+00 5.07941290e-05 2.66514806e-01 3.54848920e-02]]]


In [58]:
print((yerr**2).sum(axis=1)**0.5/3)

[[0.55535635        nan 0.73547868 1.23204649]
 [0.63126484 0.47149001        nan        nan]]
