In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

import hyclib as lib

In [3]:
d = {'a': torch.Tensor([[1.0,2.0],[3.0,4.0]]), 'b': {'c': np.array([[1.0,2.0],[3.0,4.0]]), 'd': 10.0}}

lib.pprint.pprint(d, verbose=True)

'a':
    tensor([[1., 2.],
            [3., 4.]])
'b':
    'c':
        [[1. 2.]
         [3. 4.]]
    'd':
        10.0


In [8]:
import hyclib as lib

class A:
    def __repr__(self):
        return 'repr'
        
    def __str__(self):
        return 'str'

d = {'a': [{'hi': A()}, A()], 'b': {'c': [A(), ('hi', A())], 'd': 10.0}}

lib.pprint.pprint(d)
lib.pprint.pprint(d, depth=0)
lib.pprint.pprint(d, formatters={list: lib.pprint.iter_str})

'a':
    [{'hi': repr}, repr]
'b':
    'c':
        [repr, ('hi', repr)]
    'd':
        10.0
'a':
    [{'hi': repr}, repr]
'b':
    {'c': [repr, ('hi', repr)], 'd': 10.0}
'a':
    [{'hi': str}, str]
'b':
    'c':
        [str, ('hi', str)]
    'd':
        10.0


In [10]:
string = \
"\
'a':\n\
    tensor([[1., 2.],\n\
            [3., 4.]])\n\
'b':\n\
    'c':\n\
        [[1. 2.]\n\
         [3. 4.]]\n\
    'd':\n\
        10.0\
"
print(string)

'a':
    tensor([[1., 2.],
            [3., 4.]])
'b':
    'c':
        [[1. 2.]
         [3. 4.]]
    'd':
        10.0
