In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

import utils

In [3]:
d = {'a': torch.Tensor([[1.0,2.0],[3.0,4.0]]), 'b': {'c': np.array([[1.0,2.0],[3.0,4.0]]), 'd': 10.0}}

utils.pprint.pprint(d)

'a':
    <class 'torch.Tensor'>
'b':
    'c':
        <class 'numpy.ndarray'>
    'd':
        <class 'float'>


In [10]:
string = \
"\
'a':\n\
    tensor([[1., 2.],\n\
            [3., 4.]])\n\
'b':\n\
    'c':\n\
        [[1. 2.]\n\
         [3. 4.]]\n\
    'd':\n\
        10.0\
"
print(string)

'a':
    tensor([[1., 2.],
            [3., 4.]])
'b':
    'c':
        [[1. 2.]
         [3. 4.]]
    'd':
        10.0
