In [3]:
import random

import torch
import numpy as np

import hyclib as lib

In [27]:
size = (2,)

print(torch.rand(size))
print(np.random.random(size=size))
print(random.random())

seed = 0
with lib.random.set_seed(seed):
    print(torch.rand(size))
    print(np.random.random(size=size))
    print(random.random())
    
with lib.random.set_seed(seed):
    print(torch.rand(size))
    print(np.random.random(size=size))
    print(random.random())
    
seed = 1
with lib.random.set_seed(seed):
    print(torch.rand(size))
    print(np.random.random(size=size))
    print(random.random())
    
with lib.random.set_seed(seed):
    print(torch.rand(size))
    print(np.random.random(size=size))
    print(random.random())

print(torch.rand(size))
print(np.random.random(size=size))
print(random.random())

tensor([0.1217, 0.7356])
[0.89132195 0.20920212]
0.43351443489540376
tensor([0.4963, 0.7682])
[0.5488135  0.71518937]
0.8444218515250481
tensor([0.4963, 0.7682])
[0.5488135  0.71518937]
0.8444218515250481
tensor([0.7576, 0.2793])
[0.417022   0.72032449]
0.13436424411240122
tensor([0.7576, 0.2793])
[0.417022   0.72032449]
0.13436424411240122
tensor([0.7118, 0.7876])
[0.18532822 0.10837689]
0.8000204571334277
